version: "3"
services:

  nginx:
    image: nginx:latest
    networks:
      - candidatestest_network
    ports:
    - "8080:80"
    volumes:
    - ./html:/html
    - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php

  composer:
      image: composer/composer
      networks:
        - candidatestest_network
      ports:
        - "9001:9000"
      volumes:
        - "./html:/composer"
      container_name: composer
      working_dir: /composer
      command: composer install
  
  php:
    image: php:8.1-fpm
    networks:
      - candidatestest_network
    volumes:
      - ./html:/html
    depends_on:
      - composer

# networks
networks:
  candidatestest_network: